/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

unsigned long fibonacci( long fibo_k2, long fibo_k1 ){
    return fibo_k2 + fibo_k1;

}

unsigned long getEvenFibonacciSum(unsigned long limit){
    unsigned long evensum = 0 ; 
    unsigned long fibonacci_sum = 0;
    unsigned long fibo_k1 =1;
    unsigned long fibo_k2 =1;

    while(fibonacci_sum < limit){
        if(!(fibonacci_sum & 0x1)){
            evensum+=fibonacci_sum;
        }
        fibonacci_sum = fibonacci(fibo_k2,fibo_k1);
        fibo_k2=fibo_k1;
        fibo_k1=fibonacci_sum;
    }

    return evensum;
}

int main(){
    unsigned long evensum = 0 ; 
    unsigned long limit =4000000;
    int t,i;
    scanf("%d",&t);
    for(i = 0; i < t; i++ ){
        scanf("%lu",&limit);
        evensum = getEvenFibonacciSum(limit);
        printf("%lu\n",evensum);
    }

    return 0;
}
