/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

int fibonacci( int fibo_k2,int fibo_k1 ){
    return fibo_k2 + fibo_k1;

}

int main(){
  int evensum = 0 ; 
  int i = 1 ;
  int fibonacci_sum = 0;
  int fibo_k1 =1;
  int fibo_k2 =1;
  while(fibonacci_sum < 4000000){
      fibonacci_sum = fibonacci(fibo_k2,fibo_k1);
      fibo_k2=fibo_k1;
      fibo_k1=fibonacci_sum;
      i++;
      if(!(fibonacci_sum % 2 )){
          evensum+=fibonacci_sum;
      }
  }

  printf("The sum of the even numbers is =%d \n",evensum);
  
  return 0;
}
